version: "3"

services:
  zookeeper-node1:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper-node1
    container_name: zookeeper-node1
    ports:
      - "22181:2181"
    expose:
      - "2181"
      - "22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - network_cluster_kafka

  zookeeper-node2:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper-node2
    container_name: zookeeper-node2
    ports:
      - "32181:2181"
    expose:
      - "2181"
      - "32181"    
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - network_cluster_kafka

  broker-node1:
    image: confluentinc/cp-server:5.4.0
    hostname: broker-node1
    container_name: broker-node1
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
    ports:
      - "39092:9092"
    expose:
      - "39092"
      - "9092"
    networks:
      network_cluster_kafka:
        ipv4_address: 192.169.5.4
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node1:2181,zookeeper-node2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-node1:29092,PLAINTEXT_HOST://192.169.5.4:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-node1:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper-node1:2181,zookeeper-node2:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"

  broker-node2:
    image: confluentinc/cp-server:5.4.0
    hostname: broker-node2
    container_name: broker-node2
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
    ports:
      - "49092:9092"
    expose:
      - "49092"
      - "9092"
    networks:
      network_cluster_kafka:
        ipv4_address: 192.169.5.5
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node1:2181,zookeeper-node2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-node2:29092,PLAINTEXT_HOST://192.169.5.5:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-node2:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper-node1:2181,zookeeper-node2:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"

  kafka-tools:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka-tools
    container_name: kafka-tools
    command: ["tail", "-f", "/dev/null"]
    network_mode: "host"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - broker-node1
      - broker-node2
    ports:
      - "8081:8081"
    networks:
      - network_cluster_kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-node1:2181,zookeeper-node2:2181

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.4.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper-node1
      - zookeeper-node2
      - broker-node1
      - broker-node2
      - schema-registry
    ports:
      - "9021:9021"
    networks:
      - network_cluster_kafka
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-node1:29092,broker-node2:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper-node1:2181,zookeeper-node2:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021


networks:
  network_cluster_kafka:
    external:
      name: network_cluster_kafka